server:
  port: 8080
  servlet:
    context-path: /evplatform

spring:
  main:
    banner-mode: off
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB

frontend:
  url: ${FRONTEND_URL}

jwt:
  signerKey: ${SIGNER_KEY}

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  success-url: http://localhost:5173/checkout/success?session_id={CHECKOUT_SESSION_ID}
  cancel-url: http://localhost:5173/checkout/cancel

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

app:
  checkout:
    success-url: "http://localhost:5173/inspectionCheckout/success?success=true"
    cancel-url: "http://localhost:5173/inspectionCheckout/success?success=false"
  deal:
    success-url: "http://localhost:5173/dealCheckout/success?success=true"
    cancel-url: "http://localhost:5173/dealCheckout/success?success=false"

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  upload-folder-root: sale-posts
  max-file-size-mb: 10




#logging:
#  level:
#    root: warn
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
